// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using student_resource_hub.Data;

#nullable disable

namespace student_resource_hub.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260918090705_InitialMySqlSchema")]
    partial class InitialMySqlSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("student_resource_hub.Models.AcademicDepartment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<int>("UniversityId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UniversityId", "Name")
                        .IsUnique();

                    b.ToTable("AcademicDepartments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=900&q=80",
                            IsActive = true,
                            Name = "Computer Science and Engineering",
                            UniversityId = 1
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=900&q=80",
                            IsActive = true,
                            Name = "Mechanical Engineering",
                            UniversityId = 1
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?auto=format&fit=crop&w=900&q=80",
                            IsActive = true,
                            Name = "Industrial and Production Engineering",
                            UniversityId = 1
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=900&q=80",
                            IsActive = true,
                            Name = "Civil Engineering",
                            UniversityId = 1
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=900&q=80",
                            IsActive = true,
                            Name = "Data Science",
                            UniversityId = 1
                        },
                        new
                        {
                            Id = 6,
                            ImageUrl = "https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&w=900&q=80",
                            IsActive = true,
                            Name = "Artificial Intelligence",
                            UniversityId = 1
                        },
                        new
                        {
                            Id = 7,
                            ImageUrl = "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&w=900&q=80",
                            IsActive = true,
                            Name = "Aeronautical Engineering",
                            UniversityId = 1
                        },
                        new
                        {
                            Id = 8,
                            ImageUrl = "https://images.unsplash.com/photo-1518773553398-650c184e0bb3?auto=format&fit=crop&w=900&q=80",
                            IsActive = true,
                            Name = "Software Engineering",
                            UniversityId = 1
                        });
                });

            modelBuilder.Entity("student_resource_hub.Models.AcademicSemester", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId", "Name")
                        .IsUnique();

                    b.ToTable("AcademicSemesters");

                    b.HasData(
                        new
                        {
                            Id = 11,
                            DepartmentId = 1,
                            IsActive = true,
                            Name = "Semester 1",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 12,
                            DepartmentId = 1,
                            IsActive = true,
                            Name = "Semester 2",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 13,
                            DepartmentId = 1,
                            IsActive = true,
                            Name = "Semester 3",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 14,
                            DepartmentId = 1,
                            IsActive = true,
                            Name = "Semester 4",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 15,
                            DepartmentId = 1,
                            IsActive = true,
                            Name = "Semester 5",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 16,
                            DepartmentId = 1,
                            IsActive = true,
                            Name = "Semester 6",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 17,
                            DepartmentId = 1,
                            IsActive = true,
                            Name = "Semester 7",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 18,
                            DepartmentId = 1,
                            IsActive = true,
                            Name = "Semester 8",
                            SortOrder = 8
                        },
                        new
                        {
                            Id = 21,
                            DepartmentId = 2,
                            IsActive = true,
                            Name = "Semester 1",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 22,
                            DepartmentId = 2,
                            IsActive = true,
                            Name = "Semester 2",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 23,
                            DepartmentId = 2,
                            IsActive = true,
                            Name = "Semester 3",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 24,
                            DepartmentId = 2,
                            IsActive = true,
                            Name = "Semester 4",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 25,
                            DepartmentId = 2,
                            IsActive = true,
                            Name = "Semester 5",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 26,
                            DepartmentId = 2,
                            IsActive = true,
                            Name = "Semester 6",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 27,
                            DepartmentId = 2,
                            IsActive = true,
                            Name = "Semester 7",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 28,
                            DepartmentId = 2,
                            IsActive = true,
                            Name = "Semester 8",
                            SortOrder = 8
                        },
                        new
                        {
                            Id = 31,
                            DepartmentId = 3,
                            IsActive = true,
                            Name = "Semester 1",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 32,
                            DepartmentId = 3,
                            IsActive = true,
                            Name = "Semester 2",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 33,
                            DepartmentId = 3,
                            IsActive = true,
                            Name = "Semester 3",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 34,
                            DepartmentId = 3,
                            IsActive = true,
                            Name = "Semester 4",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 35,
                            DepartmentId = 3,
                            IsActive = true,
                            Name = "Semester 5",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 36,
                            DepartmentId = 3,
                            IsActive = true,
                            Name = "Semester 6",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 37,
                            DepartmentId = 3,
                            IsActive = true,
                            Name = "Semester 7",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 38,
                            DepartmentId = 3,
                            IsActive = true,
                            Name = "Semester 8",
                            SortOrder = 8
                        },
                        new
                        {
                            Id = 41,
                            DepartmentId = 4,
                            IsActive = true,
                            Name = "Semester 1",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 42,
                            DepartmentId = 4,
                            IsActive = true,
                            Name = "Semester 2",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 43,
                            DepartmentId = 4,
                            IsActive = true,
                            Name = "Semester 3",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 44,
                            DepartmentId = 4,
                            IsActive = true,
                            Name = "Semester 4",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 45,
                            DepartmentId = 4,
                            IsActive = true,
                            Name = "Semester 5",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 46,
                            DepartmentId = 4,
                            IsActive = true,
                            Name = "Semester 6",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 47,
                            DepartmentId = 4,
                            IsActive = true,
                            Name = "Semester 7",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 48,
                            DepartmentId = 4,
                            IsActive = true,
                            Name = "Semester 8",
                            SortOrder = 8
                        },
                        new
                        {
                            Id = 51,
                            DepartmentId = 5,
                            IsActive = true,
                            Name = "Semester 1",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 52,
                            DepartmentId = 5,
                            IsActive = true,
                            Name = "Semester 2",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 53,
                            DepartmentId = 5,
                            IsActive = true,
                            Name = "Semester 3",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 54,
                            DepartmentId = 5,
                            IsActive = true,
                            Name = "Semester 4",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 55,
                            DepartmentId = 5,
                            IsActive = true,
                            Name = "Semester 5",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 56,
                            DepartmentId = 5,
                            IsActive = true,
                            Name = "Semester 6",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 57,
                            DepartmentId = 5,
                            IsActive = true,
                            Name = "Semester 7",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 58,
                            DepartmentId = 5,
                            IsActive = true,
                            Name = "Semester 8",
                            SortOrder = 8
                        },
                        new
                        {
                            Id = 61,
                            DepartmentId = 6,
                            IsActive = true,
                            Name = "Semester 1",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 62,
                            DepartmentId = 6,
                            IsActive = true,
                            Name = "Semester 2",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 63,
                            DepartmentId = 6,
                            IsActive = true,
                            Name = "Semester 3",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 64,
                            DepartmentId = 6,
                            IsActive = true,
                            Name = "Semester 4",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 65,
                            DepartmentId = 6,
                            IsActive = true,
                            Name = "Semester 5",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 66,
                            DepartmentId = 6,
                            IsActive = true,
                            Name = "Semester 6",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 67,
                            DepartmentId = 6,
                            IsActive = true,
                            Name = "Semester 7",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 68,
                            DepartmentId = 6,
                            IsActive = true,
                            Name = "Semester 8",
                            SortOrder = 8
                        },
                        new
                        {
                            Id = 71,
                            DepartmentId = 7,
                            IsActive = true,
                            Name = "Semester 1",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 72,
                            DepartmentId = 7,
                            IsActive = true,
                            Name = "Semester 2",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 73,
                            DepartmentId = 7,
                            IsActive = true,
                            Name = "Semester 3",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 74,
                            DepartmentId = 7,
                            IsActive = true,
                            Name = "Semester 4",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 75,
                            DepartmentId = 7,
                            IsActive = true,
                            Name = "Semester 5",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 76,
                            DepartmentId = 7,
                            IsActive = true,
                            Name = "Semester 6",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 77,
                            DepartmentId = 7,
                            IsActive = true,
                            Name = "Semester 7",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 78,
                            DepartmentId = 7,
                            IsActive = true,
                            Name = "Semester 8",
                            SortOrder = 8
                        },
                        new
                        {
                            Id = 81,
                            DepartmentId = 8,
                            IsActive = true,
                            Name = "Semester 1",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 82,
                            DepartmentId = 8,
                            IsActive = true,
                            Name = "Semester 2",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 83,
                            DepartmentId = 8,
                            IsActive = true,
                            Name = "Semester 3",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 84,
                            DepartmentId = 8,
                            IsActive = true,
                            Name = "Semester 4",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 85,
                            DepartmentId = 8,
                            IsActive = true,
                            Name = "Semester 5",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 86,
                            DepartmentId = 8,
                            IsActive = true,
                            Name = "Semester 6",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 87,
                            DepartmentId = 8,
                            IsActive = true,
                            Name = "Semester 7",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 88,
                            DepartmentId = 8,
                            IsActive = true,
                            Name = "Semester 8",
                            SortOrder = 8
                        });
                });

            modelBuilder.Entity("student_resource_hub.Models.AttendanceRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttendanceSessionId")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("StudentEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("AttendanceSessionId", "UserId")
                        .IsUnique();

                    b.ToTable("AttendanceRecords");
                });

            modelBuilder.Entity("student_resource_hub.Models.AttendanceSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Passcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("SessionDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SessionTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time(6)");

                    b.HasKey("Id");

                    b.HasIndex("CourseCode");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("IsActive");

                    b.HasIndex("SessionDate");

                    b.ToTable("AttendanceSessions");
                });

            modelBuilder.Entity("student_resource_hub.Models.Lecture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AcademicDepartmentId")
                        .HasColumnType("int");

                    b.Property<int?>("AcademicSemesterId")
                        .HasColumnType("int");

                    b.Property<string>("ApprovalNotes")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Department")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("DownloadCount")
                        .HasColumnType("int");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProfessorName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Semester")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Topics")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("UploadedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AcademicDepartmentId");

                    b.HasIndex("AcademicSemesterId");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("Status");

                    b.HasIndex("UploadedByUserId");

                    b.HasIndex("Department", "Year", "Semester");

                    b.ToTable("Lectures");
                });

            modelBuilder.Entity("student_resource_hub.Models.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AcademicDepartmentId")
                        .HasColumnType("int");

                    b.Property<int?>("AcademicSemesterId")
                        .HasColumnType("int");

                    b.Property<string>("ApprovalNotes")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("AverageRating")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)");

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Department")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("DownloadCount")
                        .HasColumnType("int");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("PageCount")
                        .HasColumnType("int");

                    b.Property<string>("ProfessorName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Semester")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("TotalRatings")
                        .HasColumnType("int");

                    b.Property<int>("UploadedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AcademicDepartmentId");

                    b.HasIndex("AcademicSemesterId");

                    b.HasIndex("AverageRating");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("Status");

                    b.HasIndex("UploadedByUserId");

                    b.HasIndex("Department", "Year", "Semester");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("student_resource_hub.Models.PastPaper", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AcademicDepartmentId")
                        .HasColumnType("int");

                    b.Property<int?>("AcademicSemesterId")
                        .HasColumnType("int");

                    b.Property<string>("ApprovalNotes")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Department")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("DownloadCount")
                        .HasColumnType("int");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProfessorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Semester")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("UploadedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AcademicDepartmentId");

                    b.HasIndex("AcademicSemesterId");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("Status");

                    b.HasIndex("UploadedByUserId");

                    b.HasIndex("Department", "Year", "Semester");

                    b.ToTable("PastPapers");
                });

            modelBuilder.Entity("student_resource_hub.Models.StudyFolder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<int>("StudySessionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudySessionId", "Name")
                        .IsUnique();

                    b.ToTable("StudyFolders");
                });

            modelBuilder.Entity("student_resource_hub.Models.StudyResource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CourseCode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("ResourceId")
                        .HasColumnType("int");

                    b.Property<string>("ResourceTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("StudyFolderId")
                        .HasColumnType("int");

                    b.Property<int>("StudySessionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudyFolderId");

                    b.HasIndex("StudySessionId", "ResourceType", "ResourceId")
                        .IsUnique();

                    b.ToTable("StudyResources");
                });

            modelBuilder.Entity("student_resource_hub.Models.StudySession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.ToTable("StudySessions");
                });

            modelBuilder.Entity("student_resource_hub.Models.University", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Universities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Default University"
                        });
                });

            modelBuilder.Entity("student_resource_hub.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AcademicDepartmentId")
                        .HasColumnType("int");

                    b.Property<int?>("AcademicSemesterId")
                        .HasColumnType("int");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("ProfilePhotoPath")
                        .HasMaxLength(260)
                        .HasColumnType("varchar(260)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("UniversityId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AcademicDepartmentId");

                    b.HasIndex("AcademicSemesterId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UniversityId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("student_resource_hub.Models.AcademicDepartment", b =>
                {
                    b.HasOne("student_resource_hub.Models.University", "University")
                        .WithMany("Departments")
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("University");
                });

            modelBuilder.Entity("student_resource_hub.Models.AcademicSemester", b =>
                {
                    b.HasOne("student_resource_hub.Models.AcademicDepartment", "Department")
                        .WithMany("Semesters")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("student_resource_hub.Models.AttendanceRecord", b =>
                {
                    b.HasOne("student_resource_hub.Models.AttendanceSession", "AttendanceSession")
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("AttendanceSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("student_resource_hub.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AttendanceSession");

                    b.Navigation("User");
                });

            modelBuilder.Entity("student_resource_hub.Models.AttendanceSession", b =>
                {
                    b.HasOne("student_resource_hub.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("student_resource_hub.Models.Lecture", b =>
                {
                    b.HasOne("student_resource_hub.Models.AcademicDepartment", "AcademicDepartment")
                        .WithMany()
                        .HasForeignKey("AcademicDepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("student_resource_hub.Models.AcademicSemester", "AcademicSemester")
                        .WithMany()
                        .HasForeignKey("AcademicSemesterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("student_resource_hub.Models.User", "UploadedByUser")
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AcademicDepartment");

                    b.Navigation("AcademicSemester");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("student_resource_hub.Models.Note", b =>
                {
                    b.HasOne("student_resource_hub.Models.AcademicDepartment", "AcademicDepartment")
                        .WithMany()
                        .HasForeignKey("AcademicDepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("student_resource_hub.Models.AcademicSemester", "AcademicSemester")
                        .WithMany()
                        .HasForeignKey("AcademicSemesterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("student_resource_hub.Models.User", "UploadedByUser")
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AcademicDepartment");

                    b.Navigation("AcademicSemester");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("student_resource_hub.Models.PastPaper", b =>
                {
                    b.HasOne("student_resource_hub.Models.AcademicDepartment", "AcademicDepartment")
                        .WithMany()
                        .HasForeignKey("AcademicDepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("student_resource_hub.Models.AcademicSemester", "AcademicSemester")
                        .WithMany()
                        .HasForeignKey("AcademicSemesterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("student_resource_hub.Models.User", "UploadedByUser")
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AcademicDepartment");

                    b.Navigation("AcademicSemester");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("student_resource_hub.Models.StudyFolder", b =>
                {
                    b.HasOne("student_resource_hub.Models.StudySession", "StudySession")
                        .WithMany("Folders")
                        .HasForeignKey("StudySessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudySession");
                });

            modelBuilder.Entity("student_resource_hub.Models.StudyResource", b =>
                {
                    b.HasOne("student_resource_hub.Models.StudyFolder", "StudyFolder")
                        .WithMany("Resources")
                        .HasForeignKey("StudyFolderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("student_resource_hub.Models.StudySession", "StudySession")
                        .WithMany("Resources")
                        .HasForeignKey("StudySessionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("StudyFolder");

                    b.Navigation("StudySession");
                });

            modelBuilder.Entity("student_resource_hub.Models.StudySession", b =>
                {
                    b.HasOne("student_resource_hub.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("student_resource_hub.Models.User", b =>
                {
                    b.HasOne("student_resource_hub.Models.AcademicDepartment", "AcademicDepartment")
                        .WithMany()
                        .HasForeignKey("AcademicDepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("student_resource_hub.Models.AcademicSemester", "AcademicSemester")
                        .WithMany()
                        .HasForeignKey("AcademicSemesterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("student_resource_hub.Models.University", "University")
                        .WithMany("Users")
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AcademicDepartment");

                    b.Navigation("AcademicSemester");

                    b.Navigation("University");
                });

            modelBuilder.Entity("student_resource_hub.Models.AcademicDepartment", b =>
                {
                    b.Navigation("Semesters");
                });

            modelBuilder.Entity("student_resource_hub.Models.AttendanceSession", b =>
                {
                    b.Navigation("AttendanceRecords");
                });

            modelBuilder.Entity("student_resource_hub.Models.StudyFolder", b =>
                {
                    b.Navigation("Resources");
                });

            modelBuilder.Entity("student_resource_hub.Models.StudySession", b =>
                {
                    b.Navigation("Folders");

                    b.Navigation("Resources");
                });

            modelBuilder.Entity("student_resource_hub.Models.University", b =>
                {
                    b.Navigation("Departments");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
